version: '2.2'

services:

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timesheet
    ports:
      - 3306:3306

  timesheet:
  
    image: timesheet
    build: ./
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8083:8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://myapp-mysql:3306/timesheet?autoReconnect=true&useSSL=false